/**
 * The 3D view's photographic library: what is fetched, from where, pinned.
 *
 * The 3D twin of `materials/assets/asset-spec.ts`, and the same discipline — the specification lives
 * beside the code that reads it, `tools/assets fetch:pbr` makes the files, and `pbr-catalogue.json`
 * records what was actually written. The difference is where the pixels come from: the 2D library is
 * generated by an image model, this one is **downloaded from CC0 libraries** (Poly Haven, ambientCG),
 * because a physically measured material or sky is exactly what an image model cannot give.
 *
 * Every entry is pinned by the source's own checksum, so re-running the tool a year on either writes
 * the identical bytes or refuses. Nothing here is required at runtime: a missing file is a flat
 * material or the studio environment, never an error.
 */

export type PbrLicence = 'CC0-1.0';

export interface HdriSpec {
  /** Our id for it; the catalogue is keyed by this. */
  id: string;
  source: 'polyhaven';
  /** The source's own asset id. */
  asset: string;
  resolution: '1k' | '2k';
  /** The source's published MD5 of the `.hdr` at that resolution. */
  md5: string;
  licence: PbrLicence;
  author: string;
  page: string;
}

/**
 * The sky the structure is lit by.
 *
 * **Overcast, deliberately.** A partly cloudy sky carries its own sun, baked into the picture, and
 * the 3D view already has one — the plan's (`sunInFrame`), which casts every shadow. Two suns in one
 * image is the single most obvious way a render gives itself away, and lining the photograph's sun up
 * with the plan's would only ever match its bearing, never its height. An overcast dome is the sky
 * light *without* a sun: soft fill from above, a cool reflection in the aluminium, and the direct
 * light left to the plan. Low contrast, 5300 K white balance.
 */
export const SKY_HDRI: HdriSpec = {
  id: 'sky-overcast',
  source: 'polyhaven',
  asset: 'kloofendal_overcast_puresky',
  resolution: '1k',
  md5: 'd5c53f6432193893e7dc17eb65e67409',
  licence: 'CC0-1.0',
  author: 'Greg Zaal',
  page: 'https://polyhaven.com/a/kloofendal_overcast_puresky',
};

/** Where an HDRI lands, relative to `public/assets/`. */
export function hdriFile(spec: HdriSpec): string {
  return `hdri/${spec.asset}_${spec.resolution}.hdr`;
}

/* ---------------------------------------------------------------- material sets */

/**
 * A physically based material photograph: colour, OpenGL normals and roughness (with ambient
 * occlusion where the source has it), packed by `fetch:pbr` into three square 1024 px WebP files —
 * `albedo` (sRGB), `normal`, and `orm` (R ambient occlusion, G roughness, B unused; metalness is a
 * finish's own number, because every finish here is uniformly metal or not).
 */
export type PbrSetId =
  | 'timber-oak'
  | 'timber-pine'
  | 'timber-painted'
  | 'powder-coat'
  | 'wicker'
  | 'fabric'
  | 'stone'
  | 'concrete'
  | 'gravel'
  | 'polycarbonate-flutes';

export type PbrSource =
  /** Poly Haven's per-map files, each pinned by the md5 Poly Haven publishes for it. */
  | { source: 'polyhaven'; asset: string; md5: { diffuse: string; normal: string; arm: string } }
  /** ambientCG's 1K JPG zip, pinned by its sha256 (ambientCG publishes none). */
  | { source: 'ambientcg'; asset: string; sha256: string }
  /** Drawn by the tool: there is nothing to download. */
  | { source: 'generated'; kind: 'flutes' };

export interface PbrSetSpec {
  id: PbrSetId;
  from: PbrSource;
  /** The metres one repeat of the texture covers: the source's measured size where it states one. */
  tileSizeM: number;
  /**
   * Turn the photograph a quarter so the grain runs along U — `partGeometry` lays U along a part's
   * length, so a timber set must have its grain that way. The normal map is re-swizzled with it.
   */
  rotate?: boolean;
  /** Pack the colour as grey, for a finish that tints it — paint and powder coat hide wood's hue. */
  desaturate?: boolean;
  /**
   * Ship only the normal and roughness: the colour comes from elsewhere. A floor's colour is the
   * plan painter's raster, whose joints must match the 2D plan; a stone photograph would bring its
   * own joints in the wrong places.
   */
  detailOnly?: boolean;
  /**
   * Pixels per side, when 1024 is more than the set earns. A 0.3 m weave at 512 px is still a pixel
   * every 0.6 mm, and its normal map, all fine high-contrast grain, barely compresses.
   */
  px?: number;
  author: string;
  /** The source's page. Absent for a set the tool draws. */
  page?: string;
  licence: PbrLicence;
}

const AMBIENT_CG = 'ambientCG (Lennart Demes)';

export const PBR_SETS: readonly PbrSetSpec[] = [
  {
    // Planed oak: strong figure, warm. Hardwood, and dark-stained timber tinted from it.
    id: 'timber-oak',
    from: {
      source: 'polyhaven',
      asset: 'oak_veneer_01',
      md5: {
        diffuse: '39a99df4e328d62d74f3122722a64a95',
        normal: 'd05406f5fdaf51f0d7b115b35d9af1b7',
        arm: 'dfba0f063663289248f4e887f836bdcc',
      },
    },
    tileSizeM: 1.83,
    rotate: true,
    author: 'Jenelle van Heerden',
    page: 'https://polyhaven.com/a/oak_veneer_01',
    licence: 'CC0-1.0',
  },
  {
    // Pale pine with knots: what a softwood pergola is sawn from.
    id: 'timber-pine',
    from: {
      source: 'ambientcg',
      asset: 'Wood096',
      sha256: '3aa0d5cddd866f5993c03a1a9bb036c1f7e82695cdf40f765cbea9faf91684ef',
    },
    tileSizeM: 1.2,
    rotate: true,
    author: AMBIENT_CG,
    page: 'https://ambientcg.com/view?id=Wood096',
    licence: 'CC0-1.0',
  },
  {
    // The same pine under paint: the grain still shows through the film, the knots' colour does not.
    id: 'timber-painted',
    from: {
      source: 'ambientcg',
      asset: 'Wood096',
      sha256: '3aa0d5cddd866f5993c03a1a9bb036c1f7e82695cdf40f765cbea9faf91684ef',
    },
    tileSizeM: 1.2,
    rotate: true,
    desaturate: true,
    author: AMBIENT_CG,
    page: 'https://ambientcg.com/view?id=Wood096',
    licence: 'CC0-1.0',
  },
  {
    // A fine orange-peel satin: which is what powder coat is, on steel or aluminium alike.
    id: 'powder-coat',
    from: {
      source: 'ambientcg',
      asset: 'Plastic011',
      sha256: 'f60ea94c0ecc8b0782cdbb2c5192989410ec80577ba394f8f312b8212a127da5',
    },
    tileSizeM: 1,
    desaturate: true,
    author: AMBIENT_CG,
    page: 'https://ambientcg.com/view?id=Plastic011',
    licence: 'CC0-1.0',
  },
  {
    id: 'wicker',
    from: {
      source: 'ambientcg',
      asset: 'Wicker010A',
      sha256: '8d56e864348665357568a7c5f2a09dcdce11ddfb76025266919c40d29a8cb3d9',
    },
    tileSizeM: 0.35,
    author: AMBIENT_CG,
    page: 'https://ambientcg.com/view?id=Wicker010A',
    licence: 'CC0-1.0',
  },
  {
    // A coarse linen weave: an outdoor cushion.
    id: 'fabric',
    from: {
      source: 'ambientcg',
      asset: 'Fabric030',
      sha256: '82d4d00ccf901cf4707c5489005945ab8574933fc60437e26c6737f0436699e0',
    },
    tileSizeM: 0.3,
    desaturate: true,
    px: 512,
    author: AMBIENT_CG,
    page: 'https://ambientcg.com/view?id=Fabric030',
    licence: 'CC0-1.0',
  },
  {
    // A riven, jointless stone face: the surface of a sandstone flag or a sett, not its layout.
    id: 'stone',
    from: {
      source: 'ambientcg',
      asset: 'Concrete012',
      sha256: '3424d5cbbab7191d5180f362de0792c99e6a1abd81b6eb3a431c4dfc52fefe7e',
    },
    tileSizeM: 2,
    detailOnly: true,
    author: AMBIENT_CG,
    page: 'https://ambientcg.com/view?id=Concrete012',
    licence: 'CC0-1.0',
  },
  {
    id: 'concrete',
    from: {
      source: 'polyhaven',
      asset: 'concrete_floor_01',
      md5: {
        diffuse: '187065cfc20a35eb421eac6d4f38c58f',
        normal: '3862d48eb9495b302652cac825738876',
        arm: '146fe392b094a93768ba67216ea025d1',
      },
    },
    tileSizeM: 2,
    detailOnly: true,
    author: 'Rob Tuytel',
    page: 'https://polyhaven.com/a/concrete_floor_01',
    licence: 'CC0-1.0',
  },
  {
    id: 'gravel',
    from: {
      source: 'polyhaven',
      asset: 'gravel_floor',
      md5: {
        diffuse: '4f055e1545dcf41f347600fbb01d9ac2',
        normal: '2377939c71250cf32f8b842bc4f3fe82',
        arm: 'c84786c681869232bb832910f28e0630',
      },
    },
    tileSizeM: 2.25,
    detailOnly: true,
    author: 'Jenelle van Heerden, Matterfield',
    page: 'https://polyhaven.com/a/gravel_floor',
    licence: 'CC0-1.0',
  },
  {
    /*
     * Twin-wall polycarbonate: the ribs running through the sheet, every 10 mm, along U — the
     * panel's length, which is the way a sheet's flutes run so rain drains off it. There is no
     * photograph worth having of a translucent sheet — what makes it read is the ribbing catching the
     * light — so the tool draws the normal map.
     */
    id: 'polycarbonate-flutes',
    from: { source: 'generated', kind: 'flutes' },
    tileSizeM: 0.1,
    detailOnly: true,
    author: 'Garden Studio',
    licence: 'CC0-1.0',
  },
];

export function pbrSetSpec(id: PbrSetId): PbrSetSpec {
  const spec = PBR_SETS.find((candidate) => candidate.id === id);
  if (!spec) throw new Error(`No PBR set ${id}`);
  return spec;
}

/** Where a packed map lands, relative to `public/assets/`. */
export function pbrFile(id: PbrSetId, map: 'albedo' | 'normal' | 'orm'): string {
  return `pbr/${id}/${map}.webp`;
}

/** The whole 3D photographic library may not grow past this: it is checked in. */
export const PBR_BYTE_BUDGET = 15_000_000;
